--- 
- 
  vars_prompt: 
    - 
      name: var1
      private: false
      prompt: "Enter your vrf name"
    - 
      name: var2
      private: false
      prompt: "Enter your id"
    - 
      name: var3
      private: false
      prompt: "Enter your interface Tunnel number"
    - 
      name: var4
      private: false
      prompt: "Enter your address d interface Tunnel"
    - 
      name: var5
      private: false
      prompt: "Enter your mtu"
    - 
      name: var6
      private: false
      prompt: "Enter your address source d interface Tunnel"
    - 
      name: var7
      private: false
      prompt: "Enter your address destination d interface Tunnel"
    - 
      name: var8
      private: false
      prompt: "Enter your interface Gigabit number"
    - 
      name: var9
      private: false
      prompt: "Enter your address d interface Gigabit"
    - 
      name: var10
      private: false
      prompt: "Enter your ospf number"
    - 
      name: var11
      private: false
      prompt: "Enter your area number"
    - 
      confirm: true
      name: var12
      private: true
      prompt: "Enter your preshared key"
    - 
      name: var13
      private: false
      prompt: "Enter your group number 2 5 14 15 16 "
    - 
      name: var14
      private: false
      prompt: "Enter your address voisin "
