--- 
- 
  debug: 
    msg: "Enter your vrf"
  name: vrf
- 
  ios_config: 
    host: "{{ ansible_host }}"
    lines: "ip vrf {{ item }}"
    password: admin
    username: admin
  name: "conf vrf"
  register: config
